NAME: "cakephp"
BUILD_NAMESPACE: "cakephp-example-build"
DATABASE_NAMESPACE: "cakephp-example-database"
FRONTEND_NAMESPACE: "cakephp-example-frontend"
IMAGE_NAMESPACE: "openshift"
VOLUME_CAPACITY: "1Gi"
#CAKEPHP_SECRET_SALT: "...generate..."
#CAKEPHP_SECRET_TOKEN: "...generate..."
#DATABASE_NAME: ""
#DATABASE_USER: "cakephp"
#DATABASE_PASSWORD: "...generate..."
#DATABASE_ROOT_PASSWORD: "...generate..."
#DATABASE_SERVICE_NAME: "mysql"
PHP_VERSION: "7.3-ubi8"
MYSQL_VERSION: "8.0-el8"
SOURCE_REPOSITORY_URL: "https://github.com/lees07/cakephp-ex.git"
#SOURCE_REPOSITORY_REF: ""
#CONTEXT_DIR: ""
#GITHUB_WEBHOOK_SECRET: "...generate..."
#COMPOSER_MIRROR: ""
#VERSION: "latest"
